name: mighty_notes
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  nb_utils: ^4.2.2
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  google_sign_in: ^5.0.0
  google_fonts: 2.0.0
  intl: ^0.17.0
  flutter_local_notifications: ^5.0.0+1
  google_mobile_ads: ^0.12.1+1
  apple_sign_in: ^0.1.0
  mailer: ^5.0.0

  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  cached_network_image: ^3.0.0

  mobx: 1.2.1+3
  flutter_mobx: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.5
  mobx_codegen: 1.1.2
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true
  assets:
   - images/
